spring:
  # Failed to start bean'documentationPluginsBootstrapper 에러해결
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myrestapi?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: lbh
    password: tiger
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    org.hibernate.SQL: debug